commit

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -24,11 +24,30 @@ function start() {
     if is_servicegateway_service_running; then
         echo "`date +"$FMT"`: Application '$OPENSHIFT_APP_NAME' is already running; skipping start()"
         return 0
-		else
-servicegateway &
-echo $! > $OPENSHIFT_SERVICEGATEWAY_DIR/pid/servicegateway.pid
-		echo "`date +"$FMT"`: Application '$OPENSHIFT_APP_NAME' has started" >> $logf
-    fi
+		
+	fi
+		pushd "$OPENSHIFT_REPO_DIR" > /dev/null
+    {
+        servicegatewaydir=$(cat .servicegatewaydir)
+        package=$(basename $ servicegatewaydir)
+
+        if [ -f "bin/$package" ]; then
+            echo " Starting application '$OPENSHIFT_APP_NAME' from bin/$package..."
+
+            nohup "bin/$package" >> $logf 2>&1 &
+
+            ret=$?
+            npid=$!
+            if [ $ret -eq 0 ]; then
+                echo "$npid" > "$OPENSHIFT_SERVICEGATEWAY_DIR/pid/servicegateway.pid"
+            else
+                echo "Application '$OPENSHIFT_APP_NAME' failed to start - $ret" 1>&2
+                exit $ret
+            fi
+        else
+            echo "WARN: Could not find the compiled application bin/$package, will not start"
+        fi
+    } >> $logf
 
 }
 
